# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  5., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[7, 2, 8, 6, 6, 5, 6, 6, 1, 7, 9, 0],
       [3, 4, 2, 2, 0, 4, 9, 1, 8, 5, 4, 7],
       [4, 6, 3, 9, 1, 0, 4, 0, 9, 9, 8, 7],
       [6, 6, 0, 0, 0, 4, 6, 2, 4, 8, 5, 8],
       [0, 9, 0, 0, 5, 3, 1, 5, 7, 8, 8, 4],
       [9, 6, 9, 2, 2, 3, 1, 1, 3, 0, 8, 2],
       [4, 5, 5, 6, 7, 1, 7, 1, 7, 6, 1, 7],
       [1, 3, 6, 5, 5, 0, 0, 4, 5, 5, 5, 6],
       [7, 6, 5, 4, 5, 5, 7, 5, 8, 2, 6, 9],
       [6, 2, 6, 4, 5, 9, 2, 4, 4, 8, 5, 2],
       [7, 8, 3, 6, 2, 9, 9, 8, 9, 7, 7, 8],
       [7, 0, 6, 3, 7, 5, 3, 2, 4, 4, 0, 9]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

<ipython-input-9-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[7, 2, 8, 6, 6, 5, 6, 6, 1, 7, 9, 0],
       [3, 4, 2, 2, 0, 4, 9, 1, 8, 5, 4, 7],
       [4, 6, 3, 9, 1, 0, 4, 0, 9, 9, 8, 7],
       [6, 6, 0, 0, 0, 4, 6, 2, 4, 8, 5, 8],
       [0, 9, 0, 0, 5, 3, 1, 5, 7, 8, 8, 4],
       [9, 6, 9, 2, 2, 3, 1, 1, 3, 0, 8, 2],
       [4, 5, 5, 6, 7, 1, 7, 1, 7, 6, 1, 7],
       [1, 3, 6, 5, 5, 0, 0, 4, 5, 5, 5, 6],
       [7, 6, 5, 4, 5, 5, 7, 5, 8, 2, 6, 9],
       [6, 2, 6, 4, 5, 9, 2, 4, 4, 8, 5, 2],
       [7, 8, 3, 6, 2, 9, 9, 8, 9, 7, 7, 8],
       [7, 0, 6, 3, 7, 5, 3, 2, 4, 4, 0, 9]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   7,  -7,  -7, -13,   6,  30, -18,  24,  -3,  -9,   0],
       [  0,  13,  -2,  39,  -4, -13,   5, -16,  24,  15,  15,   0],
       [  0,   9,  -9,  -9, -10,  11,  19,  -5,  -6,  14,  -7,   0],
       [  0,  33, -18,  -7,  20,   2, -10,  14,  15,  17,  15,   0],
       [  0,  -2,  32,  -7,  -7,   8,  -7,  -5,   0, -25,  29,   0],
       [  0,   7,  -1,  11,  21, -12,  32, -14,  20,  17, -21,   0],
       [  0,  -3,  12,   4,   8, -11, -18,   9,   1,   7,   7,   0],
       [  0,  13,   3,   1,   6,   4,  23,   2,  24, -17,   9,   0],
       [  0, -16,  16,  -1,   5,  24, -19,   1,  -9,  22,   2,   0],
       [  0,  28, -11,  18, -17,  20,  23,  16,  22,   7,  15,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [ ]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()